name: Build and Release

on:
  push:
    tags:
      - '*'
jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v3

      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: "-w -s"
          compress_assets: "OFF"
          asset_name: smx-${{ matrix.goarch }}
          md5sum: false
          overwrite: true
